name: generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_form_builder: ^9.3.0
  google_fonts: ^6.1.0
  provider: ^6.0.3
  bottom_navy_bar: ^6.0.0
  image_picker: ^0.8.4+3
  flutter_localizations:
      sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - l10n/

flutter_localizations:
    sdk: flutter
    intl: ^0.17.0
